name: "Windows Release"

on:
  workflow_dispatch:
    branches: main

env:
  VERSION: "2.0.4"

jobs:
  build-windows:
    name: Build Windows App
    runs-on: windows-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clone Windows Repository
        run: git clone https://${{ secrets.SECRET_KEY }}@github.com/punisher-303/Doodle-Movies-Windows.git DoodleMoviesWindows

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'DoodleMoviesWindows/package-lock.json'

      - name: Install Dependencies
        shell: cmd
        run: |
          cd DoodleMoviesWindows
          npm install

      - name: Build Provider Bundle
        shell: cmd
        run: |
          cd DoodleMoviesWindows
          npm run build

      - name: Build Portable Executable
        shell: cmd
        run: |
          cd DoodleMoviesWindows
          npm run electron:build:portable

      - name: Rename Release Files
        shell: cmd
        run: |
          cd DoodleMoviesWindows/release
          for /f "tokens=*" %%i in ('dir /b *.exe ^| findstr /v portable') do (
            ren "%%i" "DoodleMoviesWin.exe"
          )

      - name: List Files After Rename
        shell: cmd
        run: |
          cd DoodleMoviesWindows
          dir release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Build-v${{ env.VERSION }}
          path: |
            DoodleMoviesWindows/release/DoodleMoviesWin.exe

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            DoodleMoviesWindows/release/DoodleMoviesWin.exe
          tag: v9.8.7
          token: ${{ secrets.SECRET_KEY }}
          prerelease: false
          allowUpdates: true
          omitBody: true